## Numpy 2

In [1]:
import numpy as np

In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [5]:
## range function only takes integer values
list(range(0.5,10.5))

TypeError: 'float' object cannot be interpreted as an integer

In [6]:
## To counter this problem we can use arange
np.arange(0.5,10.5)

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [7]:
np.arange(0.5,10.5,0.2)

array([ 0.5,  0.7,  0.9,  1.1,  1.3,  1.5,  1.7,  1.9,  2.1,  2.3,  2.5,
        2.7,  2.9,  3.1,  3.3,  3.5,  3.7,  3.9,  4.1,  4.3,  4.5,  4.7,
        4.9,  5.1,  5.3,  5.5,  5.7,  5.9,  6.1,  6.3,  6.5,  6.7,  6.9,
        7.1,  7.3,  7.5,  7.7,  7.9,  8.1,  8.3,  8.5,  8.7,  8.9,  9.1,
        9.3,  9.5,  9.7,  9.9, 10.1, 10.3])

In [8]:
list(np.arange(0.5,10.5,2))

[0.5, 2.5, 4.5, 6.5, 8.5]

In [9]:
## It will divided the data equally as per assigned values , here data set will be divided into 20 equal parts 
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [10]:
## To generate logarithmic number by default base = 10
np.logspace(1,5)

array([1.00000000e+01, 1.20679264e+01, 1.45634848e+01, 1.75751062e+01,
       2.12095089e+01, 2.55954792e+01, 3.08884360e+01, 3.72759372e+01,
       4.49843267e+01, 5.42867544e+01, 6.55128557e+01, 7.90604321e+01,
       9.54095476e+01, 1.15139540e+02, 1.38949549e+02, 1.67683294e+02,
       2.02358965e+02, 2.44205309e+02, 2.94705170e+02, 3.55648031e+02,
       4.29193426e+02, 5.17947468e+02, 6.25055193e+02, 7.54312006e+02,
       9.10298178e+02, 1.09854114e+03, 1.32571137e+03, 1.59985872e+03,
       1.93069773e+03, 2.32995181e+03, 2.81176870e+03, 3.39322177e+03,
       4.09491506e+03, 4.94171336e+03, 5.96362332e+03, 7.19685673e+03,
       8.68511374e+03, 1.04811313e+04, 1.26485522e+04, 1.52641797e+04,
       1.84206997e+04, 2.22299648e+04, 2.68269580e+04, 3.23745754e+04,
       3.90693994e+04, 4.71486636e+04, 5.68986603e+04, 6.86648845e+04,
       8.28642773e+04, 1.00000000e+05])

In [11]:
np.logspace(1,5,10, base = 2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [12]:
## To print zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
## To print zeros with more than one dimensions
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
## 3 Dimension
np.zeros((3,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
arr + 5 

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [18]:
arr * 4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [19]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [20]:
## Identity Matrix
arr1 = np.eye(4)
arr1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
import pandas as pd 

In [22]:
pd.DataFrame(arr1)

0    1    2    3
0  1.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0  0.0  1.0  0.0
3  0.0  0.0  0.0  1.0

In [23]:
np.random.rand(2,3)

array([[0.78180586, 0.53650611, 0.79508979],
       [0.91015533, 0.7098882 , 0.81421754]])

In [24]:
np.random.randn(2,3)

array([[-0.1562747 ,  0.07995664, -0.63573665],
       [-0.5638483 ,  0.12215886, -1.16484661]])

In [25]:
arr2 = np.random.randint(1,5, (3,4))
arr2

array([[4, 4, 2, 3],
       [3, 4, 1, 3],
       [3, 3, 3, 4]])

In [26]:
arr2.size

12

In [27]:
arr2.shape

(3, 4)

In [28]:
arr2.reshape(6,2)

array([[4, 4],
       [2, 3],
       [3, 4],
       [1, 3],
       [3, 3],
       [3, 4]])

In [29]:
arr2.reshape(4,3)

array([[4, 4, 2],
       [3, 3, 4],
       [1, 3, 3],
       [3, 3, 4]])

In [30]:
arr3 = arr2.reshape(2,2,3)
arr3

array([[[4, 4, 2],
        [3, 3, 4]],

       [[1, 3, 3],
        [3, 3, 4]]])

In [31]:
arr3.ndim

3

In [32]:
arr2.reshape(4,-1)

array([[4, 4, 2],
       [3, 3, 4],
       [1, 3, 3],
       [3, 3, 4]])

Here (4,-1) Means that no of rows are 4 and no of columns are 4-1 = 3

In [33]:
arr2.reshape(3,6)

ValueError: cannot reshape array of size 12 into shape (3,6)

This shows an error as size of the array is 12 and we give 3*6 means 18

In [34]:
arr4 = arr2.reshape(2,2,3,1,1,1)
print(arr4)
print("The dimension is : ", arr4.ndim)

[[[[[[4]]]


   [[[4]]]


   [[[2]]]]



  [[[[3]]]


   [[[3]]]


   [[[4]]]]]




 [[[[[1]]]


   [[[3]]]


   [[[3]]]]



  [[[[3]]]


   [[[3]]]


   [[[4]]]]]]
The dimension is :  6


In [35]:
## (1,10) will make a dataset randomly betwwen 1 to 10 
## (5,6) will be the size of the array
arr5 = np.random.randint(1,10, (5,6))

In [36]:
arr5

array([[1, 9, 4, 5, 8, 2],
       [9, 2, 3, 6, 9, 3],
       [2, 8, 8, 9, 1, 8],
       [1, 1, 4, 2, 9, 4],
       [4, 1, 3, 7, 3, 3]])

In [37]:
## To filter out the data which are greater than 6
arr5 > 6 

array([[False,  True, False, False,  True, False],
       [ True, False, False, False,  True, False],
       [False,  True,  True,  True, False,  True],
       [False, False, False, False,  True, False],
       [False, False, False,  True, False, False]])

In [38]:
arr5[arr5>6]

array([9, 8, 9, 9, 8, 8, 9, 8, 9, 7])

In [39]:
## To extract a particular row
arr5[0]

array([1, 9, 4, 5, 8, 2])

In [40]:
## To extract a particular row with a particular columns 
## Here [0,1] are the 0th and 1st columns
arr5[0,[0,1]]

array([1, 9])

In [41]:
arr5[[0,1,2,3,4],[0]]

array([1, 9, 2, 1, 4])

In [42]:
arr5[[0],[0,1,2,3,4]]

array([1, 9, 4, 5, 8])

In [43]:
arr5[0:4, 0:3]

array([[1, 9, 4],
       [9, 2, 3],
       [2, 8, 8],
       [1, 1, 4]])

0:4 - 0 to 3rd row and 0:3 - 0 to 2nd column

In [44]:
arr5[2:4, 2:4]

array([[8, 9],
       [4, 2]])

In [45]:
arr5[2:4, [2,3]]

array([[8, 9],
       [4, 2]])

In [46]:
arr5[[2,3], [2,3]]

array([8, 2])

In [47]:
arr6 = np.random.randint(1,3,(3,3))
arr7 = np.random.randint(1,3,(3,3))
print("arr6",arr6)
print("arr7",arr7)                              

arr6 [[2 2 1]
 [2 1 2]
 [1 2 1]]
arr7 [[2 1 2]
 [2 2 1]
 [2 2 2]]


In [48]:
arr6 + arr7

array([[4, 3, 3],
       [4, 3, 3],
       [3, 4, 3]])

In [49]:
arr6 - arr7

array([[ 0,  1, -1],
       [ 0, -1,  1],
       [-1,  0, -1]])

In [51]:
## This isn't a matrix multiplication ... This is just index wise multiplication
arr6 * arr7

array([[4, 2, 2],
       [4, 2, 2],
       [2, 4, 2]])

In [52]:
## To do a matrix multiplication
arr6 @ arr7

array([[10,  8,  8],
       [10,  8,  9],
       [ 8,  7,  6]])

In [53]:
arr6 / arr7

array([[1. , 2. , 0.5],
       [1. , 0.5, 2. ],
       [0.5, 1. , 0.5]])

In [54]:
arr6 / 0

/tmp/ipykernel_113/2210782488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr6 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [55]:
## Numpy Broadcasting
arr8 = np.zeros((3,4))
arr8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [56]:
arr8 +5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [57]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [58]:
arr8 + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [67]:
b = np.array([[1,2,3]])
b

array([[1, 2, 3]])

In [68]:
arr8+b

ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [70]:
b.T

array([[1],
       [2],
       [3]])

In [71]:
## Row wise
arr9 = arr8 + b.T # (T means Transpose)

In [73]:
arr9

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [74]:
## Square root
np.sqrt(arr9)

array([[1.        , 1.        , 1.        , 1.        ],
       [1.41421356, 1.41421356, 1.41421356, 1.41421356],
       [1.73205081, 1.73205081, 1.73205081, 1.73205081]])

In [75]:
## Log of base 10
np.log10(arr9)

array([[0.        , 0.        , 0.        , 0.        ],
       [0.30103   , 0.30103   , 0.30103   , 0.30103   ],
       [0.47712125, 0.47712125, 0.47712125, 0.47712125]])

In [76]:
## Exponent Function
np.exp(arr9)

array([[ 2.71828183,  2.71828183,  2.71828183,  2.71828183],
       [ 7.3890561 ,  7.3890561 ,  7.3890561 ,  7.3890561 ],
       [20.08553692, 20.08553692, 20.08553692, 20.08553692]])

In [77]:
## Min Func
np.min(arr9)

1.0

In [78]:
## Max Func
np.max(arr9)

3.0