## Numpy 1

In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [3]:
## Converting list into a array

arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [4]:
type(arr)
## ndarray means n dimensional array

numpy.ndarray

In [5]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [6]:
arr1 = np.array([[1,2,3],[2,3,4]])

In [7]:
## To know the dimension of an array 
arr.ndim

1

In [8]:
arr1.ndim

2

In [9]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [10]:
mat = np.matrix(l)
mat

matrix([[1, 2, 3, 4, 5]])

In [11]:
mat.ndim

2

In [12]:
## It will convert any non array types thing into an array
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [13]:
## It won't work on matrix as mattrices is another type of an array 
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [14]:
arr

array([1, 2, 3, 4, 5])

In [15]:
a = arr
a

array([1, 2, 3, 4, 5])

In [16]:
arr[0] = 100
arr

array([100,   2,   3,   4,   5])

In [17]:
a

array([100,   2,   3,   4,   5])

 This is called shallow copy

In [18]:
b = np.copy(arr)
b

array([100,   2,   3,   4,   5])

In [19]:
b[0] = 7
b

array([7, 2, 3, 4, 5])

In [20]:
arr

array([100,   2,   3,   4,   5])

This is called deep copy.

In [21]:
## Construct an array by executing a function over each coordinate.
np.fromfunction(lambda i,j : i == j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [24]:
## (3,3) is shape/size of this array if i != j returns true else returns false
np.fromfunction(lambda i,j : i != j, (3,3))

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [25]:
np.fromfunction(lambda i,j : i * j, (2,2))

array([[0., 0.],
       [0., 1.]])

In [26]:
np.fromfunction(lambda i,j : i * j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [28]:
for i in range(5):
    print(i*i)

0
1
4
9
16


In [30]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [39]:
I = (i*i for i in range(5))

In [40]:
np.fromiter(I,int)

array([ 0,  1,  4,  9, 16])

In [41]:
I = (i*i for i in range(5))

In [42]:
np.fromiter(I,float) ## We have to pass data type

array([ 0.,  1.,  4.,  9., 16.])

In [43]:
np.fromstring('28 45 69', sep = ' ' )

array([28., 45., 69.])

In [47]:
np.fromstring('28, 45, 69', sep = ',' )

array([28., 45., 69.])

In [48]:
arr

array([100,   2,   3,   4,   5])

In [52]:
## To know number of elemnts in an array array
arr.size

5

In [53]:
## To know the array shape 
arr.shape

(5,)

In [56]:
arr.dtype

dtype('int64')

In [50]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [51]:
arr1.size

6

In [55]:
## matrix size 2*3
arr1.shape

(2, 3)

In [57]:
arr1.dtype

dtype('int64')