## Numpy 3

In [1]:
import numpy as np

#### Numpy Array Manipulation

In [2]:
arr = np.random.randint(1,10, (4,4))
arr

array([[7, 8, 7, 1],
       [7, 9, 5, 3],
       [5, 3, 1, 3],
       [6, 6, 8, 7]])

In [3]:
arr.reshape(8,2)

array([[7, 8],
       [7, 1],
       [7, 9],
       [5, 3],
       [5, 3],
       [1, 3],
       [6, 6],
       [8, 7]])

In [4]:
arr.reshape(2,8)

array([[7, 8, 7, 1, 7, 9, 5, 3],
       [5, 3, 1, 3, 6, 6, 8, 7]])

In [5]:
arr.T

array([[7, 7, 5, 6],
       [8, 9, 3, 6],
       [7, 5, 1, 8],
       [1, 3, 3, 7]])

In [6]:
## Return a copy of the array collapsed into one dimension.
arr.flatten()

array([7, 8, 7, 1, 7, 9, 5, 3, 5, 3, 1, 3, 6, 6, 8, 7])

In [7]:
arr

array([[7, 8, 7, 1],
       [7, 9, 5, 3],
       [5, 3, 1, 3],
       [6, 6, 8, 7]])

In [8]:
arr.ndim

2

In [9]:
## Expand Dimension
np.expand_dims(arr,axis = 1)

array([[[7, 8, 7, 1]],

       [[7, 9, 5, 3]],

       [[5, 3, 1, 3]],

       [[6, 6, 8, 7]]])

In [10]:
np.expand_dims(arr,axis = 0)

array([[[7, 8, 7, 1],
        [7, 9, 5, 3],
        [5, 3, 1, 3],
        [6, 6, 8, 7]]])

In [11]:
data = np.array([[1],[2],[3]])
data

array([[1],
       [2],
       [3]])

In [12]:
data.ndim

2

In [18]:
# squeeze the dimension
data1 = np.squeeze(data)
data1

array([1, 2, 3])

In [19]:
data1.ndim

1

In [20]:
## Repeat Data 
np.repeat(data,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [23]:
## Roll array elements along a given axis.

## Elements that roll beyond the last position are re-introduced at the first.

np.roll(data,2)

array([[2],
       [3],
       [1]])

In [24]:
np.roll(data,1)

array([[3],
       [1],
       [2]])

In [26]:
## Create a 2D array with given diagonal elements
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### Binary Operation

In [29]:
arr1 = np.random.randint(1,10, (3,4))
arr2 = np.random.randint(1,10, (3,4))

In [30]:
arr1

array([[4, 1, 9, 9],
       [1, 9, 2, 5],
       [3, 5, 5, 2]])

In [31]:
arr2

array([[3, 4, 9, 1],
       [9, 8, 2, 9],
       [2, 1, 1, 6]])

In [32]:
arr1 + arr2

array([[ 7,  5, 18, 10],
       [10, 17,  4, 14],
       [ 5,  6,  6,  8]])

In [33]:
arr1 - arr2

array([[ 1, -3,  0,  8],
       [-8,  1,  0, -4],
       [ 1,  4,  4, -4]])

In [34]:
arr1 * arr2

array([[12,  4, 81,  9],
       [ 9, 72,  4, 45],
       [ 6,  5,  5, 12]])

In [35]:
arr1 / arr2

array([[1.33333333, 0.25      , 1.        , 9.        ],
       [0.11111111, 1.125     , 1.        , 0.55555556],
       [1.5       , 5.        , 5.        , 0.33333333]])

In [36]:
## Power operation
arr1 ** arr2

array([[       64,         1, 387420489,         9],
       [        1,  43046721,         4,   1953125],
       [        9,         5,         5,        64]])

In [37]:
## Negetion Operation
~arr1

array([[ -5,  -2, -10, -10],
       [ -2, -10,  -3,  -6],
       [ -4,  -6,  -6,  -3]])

In [38]:
arr1 > arr2

array([[ True, False, False,  True],
       [False,  True, False, False],
       [ True,  True,  True, False]])

####  String Operation

In [42]:
arr3 = np.array(["arghya", "chatterjee"])
arr3

array(['arghya', 'chatterjee'], dtype='<U10')

In [43]:
np.char.upper(arr3)

array(['ARGHYA', 'CHATTERJEE'], dtype='<U10')

In [48]:
## Return a copy of `a` with only the first character of each element capitalized.
np.char.capitalize(arr3)

array(['Arghya', 'Chatterjee'], dtype='<U10')

In [47]:
## Title case words start with uppercase characters, all remaining cased characters are lowercase.
np.char.title(arr3)

array(['Arghya', 'Chatterjee'], dtype='<U10')

#### Mathematical Function

In [49]:
arr1

array([[4, 1, 9, 9],
       [1, 9, 2, 5],
       [3, 5, 5, 2]])

In [50]:
np.sin(arr1) ## Sine Value

array([[-0.7568025 ,  0.84147098,  0.41211849,  0.41211849],
       [ 0.84147098,  0.41211849,  0.90929743, -0.95892427],
       [ 0.14112001, -0.95892427, -0.95892427,  0.90929743]])

In [51]:
np.cos(arr1) ## Cosine Value

array([[-0.65364362,  0.54030231, -0.91113026, -0.91113026],
       [ 0.54030231, -0.91113026, -0.41614684,  0.28366219],
       [-0.9899925 ,  0.28366219,  0.28366219, -0.41614684]])

In [52]:
np.tan(arr1) ## Tangent Value

array([[ 1.15782128,  1.55740772, -0.45231566, -0.45231566],
       [ 1.55740772, -0.45231566, -2.18503986, -3.38051501],
       [-0.14254654, -3.38051501, -3.38051501, -2.18503986]])

In [53]:
np.log10(arr1) ## Log Value

array([[0.60205999, 0.        , 0.95424251, 0.95424251],
       [0.        , 0.95424251, 0.30103   , 0.69897   ],
       [0.47712125, 0.69897   , 0.69897   , 0.30103   ]])

In [54]:
np.exp(arr1) ## Exp Value

array([[5.45981500e+01, 2.71828183e+00, 8.10308393e+03, 8.10308393e+03],
       [2.71828183e+00, 8.10308393e+03, 7.38905610e+00, 1.48413159e+02],
       [2.00855369e+01, 1.48413159e+02, 1.48413159e+02, 7.38905610e+00]])

In [55]:
np.power(arr1,2) ## Power

array([[16,  1, 81, 81],
       [ 1, 81,  4, 25],
       [ 9, 25, 25,  4]])

In [56]:
np.mean(arr1) 

4.583333333333333

In [57]:
np.median(arr1) 

4.5

In [59]:
np.mode(arr1) ## 'numpy' has no attribute 'mode'

AttributeError: module 'numpy' has no attribute 'mode'

In [60]:
np.std(arr1) ## Standard Deviation

2.8999521068842196

In [61]:
np.var(arr1) ## Variance

8.409722222222223

In [62]:
np.min(arr1)

1

In [63]:
np.max(arr1)

9

#### Arithmetic Operation

In [64]:
arr1 

array([[4, 1, 9, 9],
       [1, 9, 2, 5],
       [3, 5, 5, 2]])

In [65]:
arr2

array([[3, 4, 9, 1],
       [9, 8, 2, 9],
       [2, 1, 1, 6]])

In [66]:
arr1 - arr2

array([[ 1, -3,  0,  8],
       [-8,  1,  0, -4],
       [ 1,  4,  4, -4]])

In [67]:
np.subtract(arr1,arr2)

array([[ 1, -3,  0,  8],
       [-8,  1,  0, -4],
       [ 1,  4,  4, -4]])

In [68]:
np.multiply(arr1,arr2)

array([[12,  4, 81,  9],
       [ 9, 72,  4, 45],
       [ 6,  5,  5, 12]])

In [69]:
np.mod(arr1,arr2)  ## Return remainder

array([[1, 1, 0, 0],
       [1, 1, 0, 5],
       [1, 0, 0, 2]])

In [70]:
np.power(arr1,arr2)

array([[       64,         1, 387420489,         9],
       [        1,  43046721,         4,   1953125],
       [        9,         5,         5,        64]])

In [71]:
np.sqrt(arr1)

array([[2.        , 1.        , 3.        , 3.        ],
       [1.        , 3.        , 1.41421356, 2.23606798],
       [1.73205081, 2.23606798, 2.23606798, 1.41421356]])